### ISSUE TITLE
can not handle 'do' clause with multi expression result returned

### ISSUE THREAD

**Issue by hanks** [smihica/arc-js#8]
```
arc>
(do (+ 1 2)
    (+ 2 3))
;; passed -- read:3ms compile:15ms eval:1ms total:19ms
5
````  
There should be two lines returned here, like:
3
5

**Comment by smihica** [comment]
Hi @hanks.
The ```(do ...)``` syntax in arc is same as ```(progn ...)``` syntax in common lisp or ```(begin ...)``` syntax in scheme.
It "executes the statements in order and returns the result of the last statements". 

please see. -> https://arclanguage.github.io/ref/variables.html#do

BTW, multiple-values (values ...) in common-lisp or scheme is not supported in arc yet.

**Comment by svetlyak40wt** [comment]
Why do you want this?
Try something like

(list (+ 1 2) (+ 2 3))

**Comment by hanks** [comment]
@smihica @svetlyak40wt Thank you for the answers, I am a new comer for arc, and just use arcjs to test some examples from a tutorial. ArcJS is a great online tool, thank you~~

**Comment by smihica** [comment]
Can I close this issue?

**Comment by hanks** [comment]
Thx
